POST http://127.0.0.1:8000/api/products/
Content-type: application/json

{
   "title": "bonehead_909090032337_26",
   "image": "https://api.cloudamqp.com/img/bone_head-223.png", 
   "likes": 20
}

###
PUT http://127.0.0.1:8000/api/products/14
Content-type: application/json

{
   "likes": 999
}

###
GET http://127.0.0.1:8000/api/products
Content-type: application/json

###
POST http://127.0.0.1:8000/api/products/14/like
Content-type: application/json
